### ISSUE TITLE
[mvn cargo] Dev Setup

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/SORMAS-Project#11]
- ~Cleanup sormas-cargo~
- ~Use development domain.xml not the production version as we currently do~
- ~autodeploy of payara and then drop the applications xml node from domain.xml~ DONE
- ~Remove sormas-serverlibs and move pom.xml to sormas-base?~
- ~Remove sormas-cargo and move it to sormas-base?~
- ~Build all artifacts with mvn install~ DONE
- ~use mvn postgres plugin instead of docker postgres?~ maintainability hazard 
- ~write documentation and emphasis that this is the easy way to kickstart SORMAS development~
- open issue in SORMAS repo
- squash commits, reference issue in commit and open PR

**Comment by MichaelSp** [comment]
nice write-up. I'd like to add:
 * [x] get the fix for a nasty cargo-bug released: https://github.com/codehaus-cargo/cargo/pull/137
 * [x] merge https://github.com/ImisDevelopers/SORMAS-Project/tree/mvn-payara-cargo
 * [ ] documentation on how to hot-swap changes in development
 * [ ] remove old dev-setup scripts and documentation to avoid confusion (needs alignment with SORMAS-Team)
 
might be relevant in this context: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2427

**Comment by JonasCir** [comment]
@jabrandes PR already targets most of this issue 2427. However, our goal is to have zero shell scripts involved and just use maven.

**Comment by MichaelSp** [comment]
maven (and docker?!)

**Comment by JonasCir** [comment]
No, I should have payed more attention sorry :D
See https://github.com/hzi-braunschweig/SORMAS-Project/pull/2375

**Comment by jabrandes** [comment]
@MichaelSp, for code hot-swap in Payara, it might be worth to take a look at https://blog.payara.fish/using-hotswapagent-to-speed-up-development. Sounds promising to me :)

**Comment by MichaelSp** [comment]
Nice pointer, thanks. Let's see if we can automate that down to just one `cargo:run` command (or something similar)

**Comment by JonasCir** [comment]
since the PR landed I go ahead and close this. Specif issues should go upstream
